import { expect, test } from '@playwright/test'

test('页面交互不阻挡导航，背景失败降级', async ({page}) => {
  let backgrounds = 0
  await page.route('https://api.yppp.net/api.php', async route => {
    backgrounds += 1
    await route.fulfill({contentType: 'image/svg+xml', body: '<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720"><rect width="1280" height="720" fill="#9acbff"/></svg>'})
  })
  await page.goto('/')
  await expect(page.locator('.wallpaper img')).toBeVisible()
  await expect(page.locator('.topbar')).toBeVisible()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('link', {name: '跳转到内容'})).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.locator('main')).toBeFocused()
  await page.locator('.instance-card').first().click()
  await page.getByRole('button', {name: '切换实例'}).click()
  await expect(page.getByRole('menuitemradio').first()).toBeVisible()
  await page.keyboard.press('Escape')
  expect(backgrounds).toBe(1)
  await page.emulateMedia({reducedMotion: 'reduce'})
  await expect(page.getByRole('button', {name: '切换实例'})).toBeVisible()
  await page.unroute('https://api.yppp.net/api.php')
  await page.route('https://api.yppp.net/api.php', route => route.abort())
  await page.reload()
  await expect(page.locator('.wallpaper img')).toHaveCount(0)
  await expect(page.getByRole('heading', {name: 'demo-main', exact: true})).toBeVisible()
})

test('总览三态、资源搭配记忆、日志与被动截图切换', async ({page}) => {
  const methods: string[] = []
  page.on('websocket', socket => socket.on('framesent', frame => { methods.push(JSON.parse(String(frame.payload)).method) }))
  await page.goto('/#/i/demo-main/overview')
  await expect(page.getByLabel('搜索日志')).toHaveCount(0)
  await expect(page.locator('.primary-nav').getByRole('link', {name: '运行日志'})).toHaveCount(0)
  await page.getByRole('button', {name: '配置资源', exact: true}).click()
  await page.getByRole('dialog').getByLabel('行动力', {exact: true}).check()
  await page.getByRole('button', {name: '完成', exact: true}).click()
  await expect(page.locator('.resource-card')).toHaveCount(5)
  await page.reload()
  await expect(page.locator('.resource-card')).toHaveCount(5)
  await page.getByRole('button', {name: '启动调度器', exact: true}).click()
  await expect(page.locator('.task-state.running')).toHaveCount(1)
  await expect(page.locator('.task-state.pending').first()).toBeVisible()
  await expect(page.locator('.task-state.waiting').first()).toBeVisible()
  await page.getByRole('tab', {name: '截图', exact: true}).click()
  await expect(page.getByAltText('任务最近一次截图')).toBeVisible({timeout: 10000})
  expect(methods).not.toContain('preview.capture')
  await page.screenshot({path: 'test-results/overview-preview-new.png', fullPage: true})
  await page.getByRole('tab', {name: '日志', exact: true}).click()
  await page.getByRole('button', {name: '展开日志筛选'}).click()
  await page.getByLabel('搜索日志').fill('模拟调度器已启动')
  await expect(page.locator('.log-line')).toHaveCount(1)
  await page.getByRole('button', {name: '停止运行', exact: true}).click()
  await page.getByLabel('搜索日志').fill('')
  await page.screenshot({path: 'test-results/overview-logs-new.png', fullPage: true})
  await page.goto('/#/i/demo-main/task/Main')
  await expect(page.locator('[id="Main.Emotion.Fleet1Record"]')).toHaveValue('2026-09-12 23:45:12.123456')
  await expect(page.locator('[id="Main.Emotion.Fleet1Record"]')).toHaveAttribute('readonly', '')
})

test('统计分类、K 线、时间过滤、表格导出与移动端布局', async ({page}) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/#/i/demo-main/statistics')
  await expect(page.getByRole('img', {name: '石油交互趋势图'})).toBeVisible()
  await page.getByLabel('图表类型').selectOption('candlestick')
  await page.getByLabel('采样粒度').selectOption('60')
  await page.screenshot({path: 'test-results/statistics-candlestick.png', fullPage: true})
  const download = page.waitForEvent('download')
  await page.getByRole('button', {name: '导出本类数据'}).click()
  expect((await download).suggestedFilename()).toMatch(/\.csv$/)
  for (const label of ['大世界趋势', '大世界总结', '委托收益', '舰船经验', '短猫掉落']) {
    await page.getByRole('navigation', {name: '统计分类'}).getByRole('button', {name: label, exact: true}).click()
    await expect(page.locator('.period-controls strong')).toHaveText(label)
  }
  await page.getByRole('button', {name: '资源趋势', exact: true}).click()
  await page.getByLabel('图表起始时间').fill('2099-01-01T00:00')
  await expect(page.getByText('这段时间没有有效记录')).toBeVisible()
  await page.getByRole('button', {name: '全部时间', exact: true}).click()
  await page.getByLabel('图表类型').selectOption('candlestick')
  await page.screenshot({path: 'test-results/statistics-resources-new.png', fullPage: true})
  await page.setViewportSize({width: 390, height: 844})
  await page.screenshot({path: 'test-results/statistics-mobile-new.png', fullPage: true})
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('下拉切换实例、创建入口与实例隔离', async ({page}) => {
  await page.goto('/#/i/demo-main/task/Alas')
  const serial = page.locator('[id="Alas.Emulator.Serial"]')
  await expect(serial).toHaveValue('127.0.0.1:5555')
  await expect(page.locator('.rail')).toHaveCount(0)
  await expect(page.locator('.primary-nav').getByRole('link', {name: '系统设置'})).toHaveCount(0)
  await expect(page.getByRole('button', {name: /保存/})).toHaveCount(0)
  await expect(page.getByRole('button', {name: '撤销修改'})).toHaveCount(0)
  await page.getByRole('button', {name: '切换实例'}).click()
  await page.getByRole('menuitemradio', {name: 'demo-alt', exact: true}).click()
  await expect(page).toHaveURL(/demo-alt\/task\/Alas/)
  await page.goto('/#/i/demo-alt/task/Alas')
  await expect(serial).toHaveValue('127.0.0.1:5557')
  await page.getByRole('button', {name: '切换实例'}).click()
  await page.keyboard.press('End')
  await expect(page.getByRole('menuitem', {name: '创建实例'})).toBeFocused()
  await page.keyboard.press('Enter')
  const name = `mock_${Date.now()}`
  await page.getByRole('dialog').getByLabel('实例名称', {exact: true}).fill(name)
  await page.getByRole('dialog').getByRole('button', {name: '创建实例', exact: true}).click()
  await expect(page).toHaveURL(new RegExp(`${name}/task/Alas`))
  await expect(serial).toBeVisible()
})

test('配置字体、多行输入与 YAML 编辑实时保存及主题颜色', async ({page}) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/#/i/demo-main/task/Alas')
  const editor = page.locator('[id="Alas.Error.OnePushConfig"]')
  await expect(editor).toBeVisible()
  await expect(page.locator('.field-label small')).toHaveCount(0)
  expect(await page.locator('.field-label label').first().evaluate(node => parseFloat(getComputedStyle(node).fontSize))).toBeGreaterThanOrEqual(14)
  expect(await page.locator('html').evaluate(node => getComputedStyle(node).zoom || '1')).toBe('1')
  const row = editor.locator('xpath=ancestor::div[contains(@class,"field-row")]')
  const label = await row.locator('.field-label').boundingBox()
  const input = await row.locator('.field-control').boundingBox()
  expect(input!.y).toBeGreaterThan(label!.y + label!.height)
  expect(input!.width).toBeGreaterThan(500)
  const yaml = '# 通知配置\nprovider: null\nretry: 3\nenabled: true\nmessage: "测试颜色"'
  await editor.fill(yaml)
  await page.waitForTimeout(500)
  await page.reload()
  await expect(editor).toHaveText(yaml.replaceAll('\n', ''))
  const token = editor.locator('span').filter({hasText: /^provider$/}).first()
  const lightColor = await token.evaluate(node => getComputedStyle(node).color)
  await row.scrollIntoViewIfNeeded()
  await page.screenshot({path: 'test-results/yaml-light.png'})
  await page.goto('/#/settings')
  await page.getByLabel('界面主题').selectOption('dark')
  await page.goto('/#/i/demo-main/task/Alas')
  await expect(editor).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  expect(await token.evaluate(node => getComputedStyle(node).color)).not.toBe(lightColor)
  await row.scrollIntoViewIfNeeded()
  await page.screenshot({path: 'test-results/yaml-dark.png'})
  const textarea = page.locator('textarea').first()
  await expect(textarea).toBeVisible()
  expect((await textarea.boundingBox())!.height).toBeLessThan(80)
  expect(errors).toEqual([])
})

test('输入框随内容和宽度变化增高，删除后缩回单行', async ({page}) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/#/i/demo-alt/task/Alas')
  const input = page.locator('textarea').first()
  await expect(input).toBeVisible()
  await input.fill('单行')
  const single = (await input.boundingBox())!.height
  expect(single).toBeLessThan(80)
  await input.fill('第一行\n第二行\n第三行\n第四行')
  expect((await input.boundingBox())!.height).toBeGreaterThan(single + 70)
  await input.fill('单行')
  expect((await input.boundingBox())!.height).toBeCloseTo(single, 0)
  await input.fill('宽度变化会触发重新计算高度。'.repeat(25))
  const wide = (await input.boundingBox())!.height
  await page.setViewportSize({width: 390, height: 844})
  await expect.poll(async () => (await input.boundingBox())!.height).toBeGreaterThan(wide)
  await input.fill('单行')
  const mobileSingle = (await input.boundingBox())!.height
  expect(mobileSingle).toBeLessThan(80)
  await input.fill('')
  expect((await input.boundingBox())!.height).toBeCloseTo(mobileSingle, 0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.setViewportSize({width: 1440, height: 1100})
  const yaml = page.locator('[id="Alas.Error.OnePushConfig"]')
  const scroller = yaml.locator('xpath=ancestor::div[contains(@class,"cm-scroller")]')
  const yamlSingle = (await scroller.boundingBox())!.height
  expect(yamlSingle).toBeLessThan(80)
  await yaml.fill('provider: null\nretry: 3\nenabled: true\nmessage: 测试')
  expect((await scroller.boundingBox())!.height).toBeGreaterThan(yamlSingle + 70)
  await yaml.fill('provider: null')
  expect((await scroller.boundingBox())!.height).toBeCloseTo(yamlSingle, 0)
  expect(errors).toEqual([])
})

test('存储空间为空时隐藏，有状态时显示完整 JSON 并可清除', async ({page}) => {
  await page.goto('/#/i/demo-alt/task/Alas')
  await expect(page.locator('textarea').first()).toBeVisible()
  await expect(page.locator('#group-Storage')).toHaveCount(0)
  await expect(page.locator('.group-nav').getByRole('link', {name: '任务状态'})).toHaveCount(0)
  await page.getByRole('textbox', {name: '搜索配置项', exact: true}).fill('Storage.Storage')
  await expect(page.getByText('没有找到配置项')).toBeVisible()
  await page.goto('/#/i/demo-error/task/Alas')
  await page.getByRole('textbox', {name: '搜索配置项', exact: true}).fill('')
  const storage = page.getByLabel('存储空间内容')
  await expect(storage).toBeVisible()
  expect(JSON.parse(await storage.innerText())).toEqual({failureCount: 3, lastError: '模拟器连接失败', retry: {enabled: false, remaining: 0}, tasks: ['Commission', 'Research']})
  await expect(storage).not.toContainText('[object Object]')
  const serial = page.locator('[id="Alas.Emulator.Serial"]')
  await serial.fill('保留其他字段的更改')
  await page.locator('#group-Storage').scrollIntoViewIfNeeded()
  await page.screenshot({path: 'test-results/storage-state.png', animations: 'disabled'})
  await page.getByRole('button', {name: '清除存储空间'}).click()
  await expect(page.locator('#group-Storage')).toHaveCount(0)
  await expect(page.locator('.group-nav').getByRole('link', {name: '任务状态'})).toHaveCount(0)
  await expect(serial).toHaveValue('保留其他字段的更改')
  await page.reload()
  await expect(page.locator('textarea').first()).toBeVisible()
  await expect(page.locator('#group-Storage')).toHaveCount(0)
})

test('语言偏好持久化，模拟启停、预览、统计和部署设置', async ({page}) => {
  await page.goto('/#/i/demo-main/settings')
  await page.getByLabel('界面语言').selectOption('en-US')
  await expect(page.locator('html')).toHaveAttribute('lang', 'en-US')
  await page.reload()
  await expect(page.getByLabel('界面语言')).toHaveValue('en-US')
  await page.goto('/#/i/demo-main/task/Alas')
  await expect(page.locator('label[for="Alas.Emulator.Serial"]')).toContainText('Serial')
  await page.goto('/#/settings')
  await page.getByLabel('界面语言').selectOption('zh-CN')
  await page.getByLabel('监听端口').fill('23456')
  await page.waitForTimeout(500)
  await page.reload()
  await expect(page.getByLabel('监听端口')).toHaveValue('23456')
  await page.goto('/#/i/demo-main/overview')
  await page.getByRole('button', {name: '启动调度器'}).click()
  await expect(page.getByRole('button', {name: '停止运行'})).toBeVisible()
  await expect(page.getByLabel('运行日志内容')).toContainText('模拟调度器已启动')
  await page.getByRole('tab', {name: '截图', exact: true}).click()
  await expect(page.getByRole('img', {name: '任务最近一次截图'})).toBeVisible()
  await page.screenshot({path: 'test-results/mock-overview.png', fullPage: true})
  await page.getByRole('button', {name: '停止运行'}).click()
  await page.locator('.primary-nav').getByRole('link', {name: '资源统计'}).click()
  await expect(page.getByRole('img', {name: /交互趋势图/})).toBeVisible()
})

test('移动端放大布局无横向溢出，单栏导航可以收起', async ({page}) => {
  await page.setViewportSize({width: 390, height: 844})
  await page.goto('/#/i/demo-main/overview')
  await page.getByRole('button', {name: '切换实例'}).click()
  await page.getByRole('menuitemradio', {name: 'demo-alt', exact: true}).click()
  await expect(page.locator('.app-shell')).not.toHaveClass(/mobile-open/)
  await page.getByRole('button', {name: '打开导航'}).click()
  await page.getByRole('link', {name: 'AzurPilot 主页'}).click()
  await page.getByRole('button', {name: '打开导航'}).click()
  await page.locator('.primary-nav').getByRole('link', {name: '系统设置'}).click()
  await expect(page.getByLabel('界面主题')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({path: 'test-results/mock-mobile.png', fullPage: true, animations: 'disabled'})
})


test('主页实例状态、任务搜索收起与导航固定', async ({page}) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', {name: /好，指挥官/})).toBeVisible()
  await expect(page.locator('.instance-card').filter({hasText: 'demo-main'})).toContainText('未运行')
  await expect(page.locator('.sidebar .instance-picker')).toHaveCount(0)
  await expect(page.locator('.sidebar-footer')).toHaveCount(0)
  await page.screenshot({path: 'test-results/home-desktop.png', fullPage: true})
  await page.locator('.instance-card').filter({hasText: 'demo-main'}).click()
  await expect(page.getByRole('heading', {name: 'demo-main', exact: true})).toBeVisible()
  await expect(page.getByLabel('搜索任务', {exact: true})).toHaveCount(0)
  await page.getByRole('button', {name: '展开任务搜索'}).click()
  await page.getByLabel('搜索任务', {exact: true}).fill('Alas')
  await expect(page.locator('.task-group-button')).toHaveCount(1)
  await page.getByRole('button', {name: '收起任务搜索'}).click()
  await expect(page.getByLabel('搜索任务', {exact: true})).toHaveCount(0)
  expect(await page.locator('.task-group-button').count()).toBeGreaterThan(1)
  await page.getByRole('button', {name: '启动调度器'}).click()
  await page.getByRole('link', {name: 'AzurPilot 主页'}).click()
  await expect(page.locator('.instance-card').filter({hasText: 'demo-main'})).toContainText('运行中')
  await expect(page.locator('.instance-card').filter({hasText: 'demo-main'})).toContainText('委托')
  await page.locator('.instance-card').filter({hasText: 'demo-main'}).click()
  await page.getByRole('button', {name: '停止运行'}).click()
  await page.goto('/#/i/demo-main/task/Alas')
  await expect(page.locator('[id="Alas.Emulator.Serial"]')).toBeVisible()
  await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight))
  expect((await page.locator('.topbar').boundingBox())!.y).toBe(12)
  await page.locator('.breadcrumb').getByRole('button', {name: '切换实例'}).click()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', {name: '切换实例'})).toBeFocused()
  expect(errors).toEqual([])
})

test('空实例主页仍可访问全局设置，系统设置不请求实例数据', async ({page}) => {
  const methods: string[] = []
  await page.routeWebSocket('**/api/v1/ws', socket => {
    const server = socket.connectToServer()
    const ids = new Set<string>()
    socket.onMessage(message => {
      const request = JSON.parse(String(message))
      methods.push(request.method)
      if (request.method === 'instances.list') ids.add(request.id)
      server.send(message)
    })
    server.onMessage(message => {
      const result = JSON.parse(String(message))
      if (ids.has(result.id)) result.result = []
      if (result.topic === 'instances') result.data = []
      socket.send(JSON.stringify(result))
    })
  })
  await page.goto('/')
  await expect(page.getByRole('button', {name: '创建第一个实例'})).toBeVisible()
  await page.locator('.primary-nav').getByRole('link', {name: '系统设置'}).click()
  await expect(page.getByLabel('界面主题')).toBeVisible()
  await expect(page.getByText('删除当前实例')).toHaveCount(0)
  expect(methods).not.toContain('startup.get')
  expect(methods).not.toContain('config.get')
  await page.setViewportSize({width: 390, height: 844})
  await page.goto('/')
  await page.screenshot({path: 'test-results/home-empty-mobile.png', fullPage: true})
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('实例列表读取失败不阻塞全局设置', async ({page}) => {
  await page.routeWebSocket('**/api/v1/ws', socket => {
    const server = socket.connectToServer()
    socket.onMessage(message => {
      const request = JSON.parse(String(message))
      if (request.method === 'instances.list') socket.send(JSON.stringify({v: 1, type: 'response', id: request.id, ok: false, error: {code: 'INTERNAL_ERROR', message: '测试实例读取失败'}}))
      else server.send(message)
    })
  })
  await page.goto('/#/settings')
  await expect(page.getByLabel('界面主题')).toBeVisible()
  await expect(page.getByLabel('监听端口')).toBeVisible()
})

test('实例设置保留自动运行和删除，删除后返回主页', async ({page}) => {
  await page.goto('/')
  await page.getByRole('button', {name: '新建实例'}).click()
  const name = `home_${Date.now()}`
  await page.getByLabel('实例名称').fill(name)
  await page.getByRole('dialog').getByRole('button', {name: '创建实例', exact: true}).click()
  await page.locator('.primary-nav').getByRole('link', {name: '运行总览', exact: true}).click()
  await page.getByRole('button', {name: '实例设置'}).click()
  await page.getByLabel('启动时自动运行', {exact: true}).check()
  await expect(page.locator('#instance-startup-status')).toHaveText('已保存')
  await page.getByRole('button', {name: '删除实例', exact: true}).click()
  await page.getByRole('button', {name: '确认删除'}).click()
  await expect(page.getByRole('heading', {name: /好，指挥官/})).toBeVisible()
  await expect(page.locator('.instance-card').filter({hasText: name})).toHaveCount(0)
})

test('导航更新提示、完整提交分页、获取和应用更新', async ({page}) => {
  await page.goto('/')
  await page.getByRole('link', {name: '新版本可用'}).click()
  await expect(page.getByRole('heading', {name: '更新器', exact: true})).toBeVisible()
  await expect(page.locator('.head-card')).toHaveCount(2)
  await expect(page.locator('.commit-row')).toHaveCount(50)
  await expect(page.locator('.commit-ref')).toHaveCount(2)
  await page.getByText('展开详情', {exact: true}).click()
  await expect(page.locator('.commit-detail pre')).toContainText('统一全局设置和更新入口')
  await page.screenshot({path: 'test-results/updater-desktop.png', fullPage: true})
  await page.getByRole('button', {name: '下一页'}).click()
  await expect(page.locator('.commit-pagination')).toContainText('51–100 / 123')
  await page.getByRole('button', {name: '下一页'}).click()
  await expect(page.locator('.commit-row')).toHaveCount(23)
  await expect(page.getByRole('button', {name: '下一页'})).toBeDisabled()
  await page.getByRole('button', {name: '获取更新', exact: true}).click()
  await page.getByRole('button', {name: '更新', exact: true}).click()
  await expect(page.getByRole('link', {name: '新版本可用'})).toHaveCount(0)
  await expect(page.locator('.update-summary')).toContainText('已是最新')
  await expect(page.locator('.commit-pagination')).toContainText('1–50 / 123')
  await page.setViewportSize({width: 390, height: 844})
  await page.screenshot({path: 'test-results/updater-mobile.png', fullPage: true})
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.goto('/#/settings')
  await page.getByLabel('界面主题').selectOption('dark')
  await page.goto('/#/updater')
  await page.screenshot({path: 'test-results/updater-dark.png'})
})
